// constants.js

const ADD_IMAGE = 'ADD_IMAGE';
const SEARCH = 'SEARCH';
const DELETE_IMAGE = 'DELETE_IMAGE'
const LOADING_IMAGE = 'LOADING_IMAGE'

export {
  ADD_IMAGE,
  SEARCH,
  DELETE_IMAGE,
  LOADING_IMAGE
};
